### ISSUE TITLE
image not scaling to full width of mappable area

### ISSUE THREAD

**Issue by tobystokes** [sylvainjule/kirby-image-annotator#2]
(great work, exactly what I have been looking for!)

If your window width is much greater than the size of the map image (which is resized to 800px)
then the mappable area/block is larger than the image itself.

![image](https://user-images.githubusercontent.com/109024/34610839-d1b6fec8-f21a-11e7-9361-2608beb081c4.png)

I think the simple fix is to 

    .imageannotator-ctn-img {
      display: inline-block
    }

Equally, you could make the image full width

    .imageannotator-img { width: 100% } 

But I think that might be a bit large in most circumstances.

**Comment by sylvainjule** [comment]
Oh, indeed, I forgot to fix it after adding the ```resize()``` helper, that's done, thanks !
